/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddProxyBinding200ResponseMeta model module.
 * @module model/AddProxyBinding200ResponseMeta
 * @version 1.0.0
 */
class AddProxyBinding200ResponseMeta {
    /**
     * Constructs a new <code>AddProxyBinding200ResponseMeta</code>.
     * @alias module:model/AddProxyBinding200ResponseMeta
     */
    constructor() { 
        
        AddProxyBinding200ResponseMeta.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddProxyBinding200ResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddProxyBinding200ResponseMeta} obj Optional instance to populate.
     * @return {module:model/AddProxyBinding200ResponseMeta} The populated <code>AddProxyBinding200ResponseMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddProxyBinding200ResponseMeta();

            if (data.hasOwnProperty('isVerificationEmailSend')) {
                obj['isVerificationEmailSend'] = ApiClient.convertToType(data['isVerificationEmailSend'], 'Boolean');
            }
            if (data.hasOwnProperty('firstProxyBinding')) {
                obj['firstProxyBinding'] = ApiClient.convertToType(data['firstProxyBinding'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddProxyBinding200ResponseMeta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddProxyBinding200ResponseMeta</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} isVerificationEmailSend
 */
AddProxyBinding200ResponseMeta.prototype['isVerificationEmailSend'] = undefined;

/**
 * @member {Boolean} firstProxyBinding
 */
AddProxyBinding200ResponseMeta.prototype['firstProxyBinding'] = undefined;






export default AddProxyBinding200ResponseMeta;

