/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddProxyBinding401ResponseInnerData from './AddProxyBinding401ResponseInnerData';

/**
 * The AddProxyBinding401ResponseInner model module.
 * @module model/AddProxyBinding401ResponseInner
 * @version 1.0.0
 */
class AddProxyBinding401ResponseInner {
    /**
     * Constructs a new <code>AddProxyBinding401ResponseInner</code>.
     * @alias module:model/AddProxyBinding401ResponseInner
     */
    constructor() { 
        
        AddProxyBinding401ResponseInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddProxyBinding401ResponseInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddProxyBinding401ResponseInner} obj Optional instance to populate.
     * @return {module:model/AddProxyBinding401ResponseInner} The populated <code>AddProxyBinding401ResponseInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddProxyBinding401ResponseInner();

            if (data.hasOwnProperty('data')) {
                obj['data'] = AddProxyBinding401ResponseInnerData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddProxyBinding401ResponseInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddProxyBinding401ResponseInner</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          AddProxyBinding401ResponseInnerData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/AddProxyBinding401ResponseInnerData} data
 */
AddProxyBinding401ResponseInner.prototype['data'] = undefined;






export default AddProxyBinding401ResponseInner;

