/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddProxyBinding401ResponseInnerDataAttributes model module.
 * @module model/AddProxyBinding401ResponseInnerDataAttributes
 * @version 1.0.0
 */
class AddProxyBinding401ResponseInnerDataAttributes {
    /**
     * Constructs a new <code>AddProxyBinding401ResponseInnerDataAttributes</code>.
     * @alias module:model/AddProxyBinding401ResponseInnerDataAttributes
     */
    constructor() { 
        
        AddProxyBinding401ResponseInnerDataAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddProxyBinding401ResponseInnerDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddProxyBinding401ResponseInnerDataAttributes} obj Optional instance to populate.
     * @return {module:model/AddProxyBinding401ResponseInnerDataAttributes} The populated <code>AddProxyBinding401ResponseInnerDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddProxyBinding401ResponseInnerDataAttributes();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('exception')) {
                obj['exception'] = ApiClient.convertToType(data['exception'], 'String');
            }
            if (data.hasOwnProperty('file')) {
                obj['file'] = ApiClient.convertToType(data['file'], 'String');
            }
            if (data.hasOwnProperty('line')) {
                obj['line'] = ApiClient.convertToType(data['line'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddProxyBinding401ResponseInnerDataAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddProxyBinding401ResponseInnerDataAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['exception'] && !(typeof data['exception'] === 'string' || data['exception'] instanceof String)) {
            throw new Error("Expected the field `exception` to be a primitive type in the JSON string but got " + data['exception']);
        }
        // ensure the json data is a string
        if (data['file'] && !(typeof data['file'] === 'string' || data['file'] instanceof String)) {
            throw new Error("Expected the field `file` to be a primitive type in the JSON string but got " + data['file']);
        }

        return true;
    }


}



/**
 * @member {String} message
 */
AddProxyBinding401ResponseInnerDataAttributes.prototype['message'] = undefined;

/**
 * @member {String} exception
 */
AddProxyBinding401ResponseInnerDataAttributes.prototype['exception'] = undefined;

/**
 * @member {String} file
 */
AddProxyBinding401ResponseInnerDataAttributes.prototype['file'] = undefined;

/**
 * @member {Number} line
 */
AddProxyBinding401ResponseInnerDataAttributes.prototype['line'] = undefined;






export default AddProxyBinding401ResponseInnerDataAttributes;

