/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload model module.
 * @module model/ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload
 * @version 1.0.0
 */
class ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload {
    /**
     * Constructs a new <code>ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload</code>.
     * @alias module:model/ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload
     */
    constructor() { 
        
        ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload} obj Optional instance to populate.
     * @return {module:model/ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload} The populated <code>ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();

            if (data.hasOwnProperty('To')) {
                obj['To'] = ApiClient.convertToType(data['To'], 'String');
            }
            if (data.hasOwnProperty('From')) {
                obj['From'] = ApiClient.convertToType(data['From'], 'String');
            }
            if (data.hasOwnProperty('Subject')) {
                obj['Subject'] = ApiClient.convertToType(data['Subject'], 'String');
            }
            if (data.hasOwnProperty('recipient')) {
                obj['recipient'] = ApiClient.convertToType(data['recipient'], 'String');
            }
            if (data.hasOwnProperty('sender')) {
                obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
            }
            if (data.hasOwnProperty('body-html')) {
                obj['body-html'] = ApiClient.convertToType(data['body-html'], 'String');
            }
            if (data.hasOwnProperty('body-plain')) {
                obj['body-plain'] = ApiClient.convertToType(data['body-plain'], 'String');
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['To'] && !(typeof data['To'] === 'string' || data['To'] instanceof String)) {
            throw new Error("Expected the field `To` to be a primitive type in the JSON string but got " + data['To']);
        }
        // ensure the json data is a string
        if (data['From'] && !(typeof data['From'] === 'string' || data['From'] instanceof String)) {
            throw new Error("Expected the field `From` to be a primitive type in the JSON string but got " + data['From']);
        }
        // ensure the json data is a string
        if (data['Subject'] && !(typeof data['Subject'] === 'string' || data['Subject'] instanceof String)) {
            throw new Error("Expected the field `Subject` to be a primitive type in the JSON string but got " + data['Subject']);
        }
        // ensure the json data is a string
        if (data['recipient'] && !(typeof data['recipient'] === 'string' || data['recipient'] instanceof String)) {
            throw new Error("Expected the field `recipient` to be a primitive type in the JSON string but got " + data['recipient']);
        }
        // ensure the json data is a string
        if (data['sender'] && !(typeof data['sender'] === 'string' || data['sender'] instanceof String)) {
            throw new Error("Expected the field `sender` to be a primitive type in the JSON string but got " + data['sender']);
        }
        // ensure the json data is a string
        if (data['body-html'] && !(typeof data['body-html'] === 'string' || data['body-html'] instanceof String)) {
            throw new Error("Expected the field `body-html` to be a primitive type in the JSON string but got " + data['body-html']);
        }
        // ensure the json data is a string
        if (data['body-plain'] && !(typeof data['body-plain'] === 'string' || data['body-plain'] instanceof String)) {
            throw new Error("Expected the field `body-plain` to be a primitive type in the JSON string but got " + data['body-plain']);
        }
        // ensure the json data is a string
        if (data['attachments'] && !(typeof data['attachments'] === 'string' || data['attachments'] instanceof String)) {
            throw new Error("Expected the field `attachments` to be a primitive type in the JSON string but got " + data['attachments']);
        }

        return true;
    }


}



/**
 * @member {String} To
 */
ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload.prototype['To'] = undefined;

/**
 * @member {String} From
 */
ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload.prototype['From'] = undefined;

/**
 * @member {String} Subject
 */
ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload.prototype['Subject'] = undefined;

/**
 * @member {String} recipient
 */
ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload.prototype['recipient'] = undefined;

/**
 * @member {String} sender
 */
ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload.prototype['sender'] = undefined;

/**
 * @member {String} body-html
 */
ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload.prototype['body-html'] = undefined;

/**
 * @member {String} body-plain
 */
ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload.prototype['body-plain'] = undefined;

/**
 * @member {String} attachments
 */
ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload.prototype['attachments'] = undefined;






export default ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload;

