/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiV1ProxyBindingsGet200ResponseMeta model module.
 * @module model/ApiV1ProxyBindingsGet200ResponseMeta
 * @version 1.0.0
 */
class ApiV1ProxyBindingsGet200ResponseMeta {
    /**
     * Constructs a new <code>ApiV1ProxyBindingsGet200ResponseMeta</code>.
     * @alias module:model/ApiV1ProxyBindingsGet200ResponseMeta
     */
    constructor() { 
        
        ApiV1ProxyBindingsGet200ResponseMeta.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiV1ProxyBindingsGet200ResponseMeta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1ProxyBindingsGet200ResponseMeta} obj Optional instance to populate.
     * @return {module:model/ApiV1ProxyBindingsGet200ResponseMeta} The populated <code>ApiV1ProxyBindingsGet200ResponseMeta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1ProxyBindingsGet200ResponseMeta();

            if (data.hasOwnProperty('usedProxyBindings')) {
                obj['usedProxyBindings'] = ApiClient.convertToType(data['usedProxyBindings'], 'Number');
            }
            if (data.hasOwnProperty('availableProxyBindings')) {
                obj['availableProxyBindings'] = ApiClient.convertToType(data['availableProxyBindings'], 'Number');
            }
            if (data.hasOwnProperty('isVerificationEmailSend')) {
                obj['isVerificationEmailSend'] = ApiClient.convertToType(data['isVerificationEmailSend'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1ProxyBindingsGet200ResponseMeta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1ProxyBindingsGet200ResponseMeta</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} usedProxyBindings
 */
ApiV1ProxyBindingsGet200ResponseMeta.prototype['usedProxyBindings'] = undefined;

/**
 * @member {Number} availableProxyBindings
 */
ApiV1ProxyBindingsGet200ResponseMeta.prototype['availableProxyBindings'] = undefined;

/**
 * @member {Boolean} isVerificationEmailSend
 */
ApiV1ProxyBindingsGet200ResponseMeta.prototype['isVerificationEmailSend'] = undefined;






export default ApiV1ProxyBindingsGet200ResponseMeta;

