/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner model module.
 * @module model/ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner
 * @version 1.0.0
 */
class ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner {
    /**
     * Constructs a new <code>ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner</code>.
     * @alias module:model/ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner
     */
    constructor() { 
        
        ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner} obj Optional instance to populate.
     * @return {module:model/ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner} The populated <code>ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }

        return true;
    }


}



/**
 * @member {String} url
 */
ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner.prototype['url'] = undefined;






export default ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesAttachmentsInner;

