/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthRequestDataAttributes from './AuthRequestDataAttributes';

/**
 * The AuthRequestData model module.
 * @module model/AuthRequestData
 * @version 1.0.0
 */
class AuthRequestData {
    /**
     * Constructs a new <code>AuthRequestData</code>.
     * @alias module:model/AuthRequestData
     */
    constructor() { 
        
        AuthRequestData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthRequestData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthRequestData} obj Optional instance to populate.
     * @return {module:model/AuthRequestData} The populated <code>AuthRequestData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthRequestData();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = AuthRequestDataAttributes.constructFromObject(data['attributes']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthRequestData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthRequestData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          AuthRequestDataAttributes.validateJSON(data['attributes']);
        }

        return true;
    }


}



/**
 * @member {module:model/AuthRequestData.TypeEnum} type
 */
AuthRequestData.prototype['type'] = undefined;

/**
 * @member {module:model/AuthRequestDataAttributes} attributes
 */
AuthRequestData.prototype['attributes'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
AuthRequestData['TypeEnum'] = {

    /**
     * value: "auth-request"
     * @const
     */
    "auth-request": "auth-request"
};



export default AuthRequestData;

