/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreatedCallback model module.
 * @module model/CreatedCallback
 * @version 1.0.0
 */
class CreatedCallback {
    /**
     * Constructs a new <code>CreatedCallback</code>.
     * @alias module:model/CreatedCallback
     */
    constructor() { 
        
        CreatedCallback.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreatedCallback</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatedCallback} obj Optional instance to populate.
     * @return {module:model/CreatedCallback} The populated <code>CreatedCallback</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatedCallback();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('call_url')) {
                obj['call_url'] = ApiClient.convertToType(data['call_url'], 'String');
            }
            if (data.hasOwnProperty('get_url')) {
                obj['get_url'] = ApiClient.convertToType(data['get_url'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreatedCallback</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreatedCallback</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['call_url'] && !(typeof data['call_url'] === 'string' || data['call_url'] instanceof String)) {
            throw new Error("Expected the field `call_url` to be a primitive type in the JSON string but got " + data['call_url']);
        }
        // ensure the json data is a string
        if (data['get_url'] && !(typeof data['get_url'] === 'string' || data['get_url'] instanceof String)) {
            throw new Error("Expected the field `get_url` to be a primitive type in the JSON string but got " + data['get_url']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}



/**
 * @member {String} status
 */
CreatedCallback.prototype['status'] = undefined;

/**
 * @member {String} call_url
 */
CreatedCallback.prototype['call_url'] = undefined;

/**
 * @member {String} get_url
 */
CreatedCallback.prototype['get_url'] = undefined;

/**
 * @member {String} id
 */
CreatedCallback.prototype['id'] = undefined;






export default CreatedCallback;

