/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OauthAccessTokenDataAttributes model module.
 * @module model/OauthAccessTokenDataAttributes
 * @version 1.0.0
 */
class OauthAccessTokenDataAttributes {
    /**
     * Constructs a new <code>OauthAccessTokenDataAttributes</code>.
     * @alias module:model/OauthAccessTokenDataAttributes
     */
    constructor() { 
        
        OauthAccessTokenDataAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OauthAccessTokenDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OauthAccessTokenDataAttributes} obj Optional instance to populate.
     * @return {module:model/OauthAccessTokenDataAttributes} The populated <code>OauthAccessTokenDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OauthAccessTokenDataAttributes();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('expires_at')) {
                obj['expires_at'] = ApiClient.convertToType(data['expires_at'], 'String');
            }
            if (data.hasOwnProperty('2fa_granted')) {
                obj['2fa_granted'] = ApiClient.convertToType(data['2fa_granted'], 'Number');
            }
            if (data.hasOwnProperty('isNewAcc')) {
                obj['isNewAcc'] = ApiClient.convertToType(data['isNewAcc'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OauthAccessTokenDataAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OauthAccessTokenDataAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['expires_at'] && !(typeof data['expires_at'] === 'string' || data['expires_at'] instanceof String)) {
            throw new Error("Expected the field `expires_at` to be a primitive type in the JSON string but got " + data['expires_at']);
        }

        return true;
    }


}



/**
 * @member {String} token
 */
OauthAccessTokenDataAttributes.prototype['token'] = undefined;

/**
 * @member {String} expires_at
 */
OauthAccessTokenDataAttributes.prototype['expires_at'] = undefined;

/**
 * @member {Number} 2fa_granted
 */
OauthAccessTokenDataAttributes.prototype['2fa_granted'] = undefined;

/**
 * @member {Boolean} isNewAcc
 */
OauthAccessTokenDataAttributes.prototype['isNewAcc'] = undefined;






export default OauthAccessTokenDataAttributes;

