/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OauthAccessTokenDataAttributes from './OauthAccessTokenDataAttributes';
import OauthAccessTokenDataRelationships from './OauthAccessTokenDataRelationships';

/**
 * The OauthAccessTokenData model module.
 * @module model/OauthAccessTokenData
 * @version 1.0.0
 */
class OauthAccessTokenData {
    /**
     * Constructs a new <code>OauthAccessTokenData</code>.
     * @alias module:model/OauthAccessTokenData
     */
    constructor() { 
        
        OauthAccessTokenData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OauthAccessTokenData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OauthAccessTokenData} obj Optional instance to populate.
     * @return {module:model/OauthAccessTokenData} The populated <code>OauthAccessTokenData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OauthAccessTokenData();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = OauthAccessTokenDataAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('relationships')) {
                obj['relationships'] = OauthAccessTokenDataRelationships.constructFromObject(data['relationships']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OauthAccessTokenData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OauthAccessTokenData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          OauthAccessTokenDataAttributes.validateJSON(data['attributes']);
        }
        // validate the optional field `relationships`
        if (data['relationships']) { // data not null
          OauthAccessTokenDataRelationships.validateJSON(data['relationships']);
        }

        return true;
    }


}



/**
 * @member {module:model/OauthAccessTokenData.TypeEnum} type
 */
OauthAccessTokenData.prototype['type'] = undefined;

/**
 * @member {String} id
 */
OauthAccessTokenData.prototype['id'] = undefined;

/**
 * @member {module:model/OauthAccessTokenDataAttributes} attributes
 */
OauthAccessTokenData.prototype['attributes'] = undefined;

/**
 * @member {module:model/OauthAccessTokenDataRelationships} relationships
 */
OauthAccessTokenData.prototype['relationships'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
OauthAccessTokenData['TypeEnum'] = {

    /**
     * value: "oauth-access-tokens"
     * @const
     */
    "oauth-access-tokens": "oauth-access-tokens"
};



export default OauthAccessTokenData;

