/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProxyBindingList from './ProxyBindingList';

/**
 * The PatchProxyBindingRequestInner model module.
 * @module model/PatchProxyBindingRequestInner
 * @version 1.0.0
 */
class PatchProxyBindingRequestInner {
    /**
     * Constructs a new <code>PatchProxyBindingRequestInner</code>.
     * @alias module:model/PatchProxyBindingRequestInner
     */
    constructor() { 
        
        PatchProxyBindingRequestInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchProxyBindingRequestInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchProxyBindingRequestInner} obj Optional instance to populate.
     * @return {module:model/PatchProxyBindingRequestInner} The populated <code>PatchProxyBindingRequestInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchProxyBindingRequestInner();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ProxyBindingList.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PatchProxyBindingRequestInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PatchProxyBindingRequestInner</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {module:model/ProxyBindingList} data
 */
PatchProxyBindingRequestInner.prototype['data'] = undefined;






export default PatchProxyBindingRequestInner;

