/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProxyBindingCreateDataAttributes model module.
 * @module model/ProxyBindingCreateDataAttributes
 * @version 1.0.0
 */
class ProxyBindingCreateDataAttributes {
    /**
     * Constructs a new <code>ProxyBindingCreateDataAttributes</code>.
     * @alias module:model/ProxyBindingCreateDataAttributes
     */
    constructor() { 
        
        ProxyBindingCreateDataAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProxyBindingCreateDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProxyBindingCreateDataAttributes} obj Optional instance to populate.
     * @return {module:model/ProxyBindingCreateDataAttributes} The populated <code>ProxyBindingCreateDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProxyBindingCreateDataAttributes();

            if (data.hasOwnProperty('real_addresses')) {
                obj['real_addresses'] = ApiClient.convertToType(data['real_addresses'], ['String']);
            }
            if (data.hasOwnProperty('proxy_address')) {
                obj['proxy_address'] = ApiClient.convertToType(data['proxy_address'], 'String');
            }
            if (data.hasOwnProperty('callback_url')) {
                obj['callback_url'] = ApiClient.convertToType(data['callback_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProxyBindingCreateDataAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProxyBindingCreateDataAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['real_addresses'])) {
            throw new Error("Expected the field `real_addresses` to be an array in the JSON data but got " + data['real_addresses']);
        }
        // ensure the json data is a string
        if (data['proxy_address'] && !(typeof data['proxy_address'] === 'string' || data['proxy_address'] instanceof String)) {
            throw new Error("Expected the field `proxy_address` to be a primitive type in the JSON string but got " + data['proxy_address']);
        }
        // ensure the json data is a string
        if (data['callback_url'] && !(typeof data['callback_url'] === 'string' || data['callback_url'] instanceof String)) {
            throw new Error("Expected the field `callback_url` to be a primitive type in the JSON string but got " + data['callback_url']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} real_addresses
 */
ProxyBindingCreateDataAttributes.prototype['real_addresses'] = undefined;

/**
 * @member {String} proxy_address
 */
ProxyBindingCreateDataAttributes.prototype['proxy_address'] = undefined;

/**
 * @member {String} callback_url
 */
ProxyBindingCreateDataAttributes.prototype['callback_url'] = undefined;






export default ProxyBindingCreateDataAttributes;

