/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProxyBindingListAttributesRealAddressesValue model module.
 * @module model/ProxyBindingListAttributesRealAddressesValue
 * @version 1.0.0
 */
class ProxyBindingListAttributesRealAddressesValue {
    /**
     * Constructs a new <code>ProxyBindingListAttributesRealAddressesValue</code>.
     * @alias module:model/ProxyBindingListAttributesRealAddressesValue
     */
    constructor() { 
        
        ProxyBindingListAttributesRealAddressesValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProxyBindingListAttributesRealAddressesValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProxyBindingListAttributesRealAddressesValue} obj Optional instance to populate.
     * @return {module:model/ProxyBindingListAttributesRealAddressesValue} The populated <code>ProxyBindingListAttributesRealAddressesValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProxyBindingListAttributesRealAddressesValue();

            if (data.hasOwnProperty('is_enabled')) {
                obj['is_enabled'] = ApiClient.convertToType(data['is_enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('is_verification_needed')) {
                obj['is_verification_needed'] = ApiClient.convertToType(data['is_verification_needed'], 'Boolean');
            }
            if (data.hasOwnProperty('is_verified')) {
                obj['is_verified'] = ApiClient.convertToType(data['is_verified'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProxyBindingListAttributesRealAddressesValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProxyBindingListAttributesRealAddressesValue</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} is_enabled
 */
ProxyBindingListAttributesRealAddressesValue.prototype['is_enabled'] = undefined;

/**
 * @member {Boolean} is_verification_needed
 */
ProxyBindingListAttributesRealAddressesValue.prototype['is_verification_needed'] = undefined;

/**
 * @member {Boolean} is_verified
 */
ProxyBindingListAttributesRealAddressesValue.prototype['is_verified'] = undefined;






export default ProxyBindingListAttributesRealAddressesValue;

