/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProxyBindingCreateData from './ProxyBindingCreateData';

/**
 * The ProxyBindingCreate model module.
 * @module model/ProxyBindingCreate
 * @version 1.0.0
 */
class ProxyBindingCreate {
    /**
     * Constructs a new <code>ProxyBindingCreate</code>.
     * @alias module:model/ProxyBindingCreate
     */
    constructor() { 
        
        ProxyBindingCreate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProxyBindingCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProxyBindingCreate} obj Optional instance to populate.
     * @return {module:model/ProxyBindingCreate} The populated <code>ProxyBindingCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProxyBindingCreate();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ProxyBindingCreateData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProxyBindingCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProxyBindingCreate</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          ProxyBindingCreateData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/ProxyBindingCreateData} data
 */
ProxyBindingCreate.prototype['data'] = undefined;






export default ProxyBindingCreate;

