/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProxyBindingListAttributesRealAddressesValue from './ProxyBindingListAttributesRealAddressesValue';

/**
 * The ProxyBindingListAttributes model module.
 * @module model/ProxyBindingListAttributes
 * @version 1.0.0
 */
class ProxyBindingListAttributes {
    /**
     * Constructs a new <code>ProxyBindingListAttributes</code>.
     * @alias module:model/ProxyBindingListAttributes
     */
    constructor() { 
        
        ProxyBindingListAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProxyBindingListAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProxyBindingListAttributes} obj Optional instance to populate.
     * @return {module:model/ProxyBindingListAttributes} The populated <code>ProxyBindingListAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProxyBindingListAttributes();

            if (data.hasOwnProperty('real_addresses')) {
                obj['real_addresses'] = ApiClient.convertToType(data['real_addresses'], {'String': ProxyBindingListAttributesRealAddressesValue});
            }
            if (data.hasOwnProperty('proxy_address')) {
                obj['proxy_address'] = ApiClient.convertToType(data['proxy_address'], 'String');
            }
            if (data.hasOwnProperty('received_emails')) {
                obj['received_emails'] = ApiClient.convertToType(data['received_emails'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('callback_url')) {
                obj['callback_url'] = ApiClient.convertToType(data['callback_url'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProxyBindingListAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProxyBindingListAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['proxy_address'] && !(typeof data['proxy_address'] === 'string' || data['proxy_address'] instanceof String)) {
            throw new Error("Expected the field `proxy_address` to be a primitive type in the JSON string but got " + data['proxy_address']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['callback_url'] && !(typeof data['callback_url'] === 'string' || data['callback_url'] instanceof String)) {
            throw new Error("Expected the field `callback_url` to be a primitive type in the JSON string but got " + data['callback_url']);
        }
        // ensure the json data is a string
        if (data['created_at'] && !(typeof data['created_at'] === 'string' || data['created_at'] instanceof String)) {
            throw new Error("Expected the field `created_at` to be a primitive type in the JSON string but got " + data['created_at']);
        }
        // ensure the json data is a string
        if (data['updated_at'] && !(typeof data['updated_at'] === 'string' || data['updated_at'] instanceof String)) {
            throw new Error("Expected the field `updated_at` to be a primitive type in the JSON string but got " + data['updated_at']);
        }

        return true;
    }


}



/**
 * @member {Object.<String, module:model/ProxyBindingListAttributesRealAddressesValue>} real_addresses
 */
ProxyBindingListAttributes.prototype['real_addresses'] = undefined;

/**
 * @member {String} proxy_address
 */
ProxyBindingListAttributes.prototype['proxy_address'] = undefined;

/**
 * @member {Number} received_emails
 */
ProxyBindingListAttributes.prototype['received_emails'] = undefined;

/**
 * @member {String} description
 */
ProxyBindingListAttributes.prototype['description'] = undefined;

/**
 * @member {String} callback_url
 */
ProxyBindingListAttributes.prototype['callback_url'] = undefined;

/**
 * @member {String} created_at
 */
ProxyBindingListAttributes.prototype['created_at'] = undefined;

/**
 * @member {String} updated_at
 */
ProxyBindingListAttributes.prototype['updated_at'] = undefined;






export default ProxyBindingListAttributes;

