/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreatedCallback from '../model/CreatedCallback';
import GetCallback from '../model/GetCallback';

/**
* Callback service.
* @module api/CallbackApi
* @version 1.0.0
*/
export default class CallbackApi {

    /**
    * Constructs a new CallbackApi. 
    * @alias module:api/CallbackApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addCallback operation.
     * @callback module:api/CallbackApi~addCallbackCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreatedCallback} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Auhtorization
     * 
     * @param {module:api/CallbackApi~addCallbackCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreatedCallback}
     */
    addCallback(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_auth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CreatedCallback;
      return this.apiClient.callApi(
        '/api/v1/callback', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the apiV1CallbackGetHashGet operation.
     * @callback module:api/CallbackApi~apiV1CallbackGetHashGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetCallback} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Auhtorization
     * 
     * @param {String} hash Callback hash
     * @param {module:api/CallbackApi~apiV1CallbackGetHashGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetCallback}
     */
    apiV1CallbackGetHashGet(hash, callback) {
      let postBody = null;
      // verify the required parameter 'hash' is set
      if (hash === undefined || hash === null) {
        throw new Error("Missing the required parameter 'hash' when calling apiV1CallbackGetHashGet");
      }

      let pathParams = {
        'hash': hash
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetCallback;
      return this.apiClient.callApi(
        '/api/v1/callback/get/{hash}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
