/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AddProxyBinding401ResponseInner from '../model/AddProxyBinding401ResponseInner';
import AuthRequest from '../model/AuthRequest';
import OauthAccessToken from '../model/OauthAccessToken';

/**
* User service.
* @module api/UserApi
* @version 1.0.0
*/
export default class UserApi {

    /**
    * Constructs a new UserApi. 
    * @alias module:api/UserApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the userAuth operation.
     * @callback module:api/UserApi~userAuthCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OauthAccessToken} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Auhtorization
     * 
     * @param {Object} opts Optional parameters
     * @param {module:model/AuthRequest} [authRequest] 
     * @param {module:api/UserApi~userAuthCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OauthAccessToken}
     */
    userAuth(opts, callback) {
      opts = opts || {};
      let postBody = opts['authRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = OauthAccessToken;
      return this.apiClient.callApi(
        '/api/v1/auth', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
