/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxiedMailApi);
  }
}(this, function(expect, ProxiedMailApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxiedMailApi.AddProxyBinding401ResponseInnerDataAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AddProxyBinding401ResponseInnerDataAttributes', function() {
    it('should create an instance of AddProxyBinding401ResponseInnerDataAttributes', function() {
      // uncomment below and update the code to test AddProxyBinding401ResponseInnerDataAttributes
      //var instance = new ProxiedMailApi.AddProxyBinding401ResponseInnerDataAttributes();
      //expect(instance).to.be.a(ProxiedMailApi.AddProxyBinding401ResponseInnerDataAttributes);
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new ProxiedMailApi.AddProxyBinding401ResponseInnerDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property exception (base name: "exception")', function() {
      // uncomment below and update the code to test the property exception
      //var instance = new ProxiedMailApi.AddProxyBinding401ResponseInnerDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instance = new ProxiedMailApi.AddProxyBinding401ResponseInnerDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property line (base name: "line")', function() {
      // uncomment below and update the code to test the property line
      //var instance = new ProxiedMailApi.AddProxyBinding401ResponseInnerDataAttributes();
      //expect(instance).to.be();
    });

  });

}));
