/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxiedMailApi);
  }
}(this, function(expect, ProxiedMailApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes', function() {
    it('should create an instance of ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes', function() {
      // uncomment below and update the code to test ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes();
      //expect(instance).to.be.a(ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes);
    });

    it('should have the property recipientEmail (base name: "recipient_email")', function() {
      // uncomment below and update the code to test the property recipientEmail
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes();
      //expect(instance).to.be();
    });

    it('should have the property senderEmail (base name: "sender_email")', function() {
      // uncomment below and update the code to test the property senderEmail
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes();
      //expect(instance).to.be();
    });

    it('should have the property attachmentsCounter (base name: "attachmentsCounter")', function() {
      // uncomment below and update the code to test the property attachmentsCounter
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes();
      //expect(instance).to.be();
    });

    it('should have the property link (base name: "link")', function() {
      // uncomment below and update the code to test the property link
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes();
      //expect(instance).to.be();
    });

    it('should have the property isProcessed (base name: "is_processed")', function() {
      // uncomment below and update the code to test the property isProcessed
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsLinksProxyBindingIdGet200ResponseAttributes();
      //expect(instance).to.be();
    });

  });

}));
