/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxiedMailApi);
  }
}(this, function(expect, ProxiedMailApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload', function() {
    it('should create an instance of ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload', function() {
      // uncomment below and update the code to test ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();
      //expect(instance).to.be.a(ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload);
    });

    it('should have the property to (base name: "To")', function() {
      // uncomment below and update the code to test the property to
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();
      //expect(instance).to.be();
    });

    it('should have the property from (base name: "From")', function() {
      // uncomment below and update the code to test the property from
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "Subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();
      //expect(instance).to.be();
    });

    it('should have the property recipient (base name: "recipient")', function() {
      // uncomment below and update the code to test the property recipient
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();
      //expect(instance).to.be();
    });

    it('should have the property sender (base name: "sender")', function() {
      // uncomment below and update the code to test the property sender
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();
      //expect(instance).to.be();
    });

    it('should have the property bodyHtml (base name: "body-html")', function() {
      // uncomment below and update the code to test the property bodyHtml
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();
      //expect(instance).to.be();
    });

    it('should have the property bodyPlain (base name: "body-plain")', function() {
      // uncomment below and update the code to test the property bodyPlain
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();
      //expect(instance).to.be();
    });

    it('should have the property attachments (base name: "attachments")', function() {
      // uncomment below and update the code to test the property attachments
      //var instance = new ProxiedMailApi.ApiV1ReceivedEmailsReceivedEmailIdGet200ResponseAttributesPayload();
      //expect(instance).to.be();
    });

  });

}));
