/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxiedMailApi);
  }
}(this, function(expect, ProxiedMailApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxiedMailApi.ProxyBindingListAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProxyBindingListAttributes', function() {
    it('should create an instance of ProxyBindingListAttributes', function() {
      // uncomment below and update the code to test ProxyBindingListAttributes
      //var instance = new ProxiedMailApi.ProxyBindingListAttributes();
      //expect(instance).to.be.a(ProxiedMailApi.ProxyBindingListAttributes);
    });

    it('should have the property realAddresses (base name: "real_addresses")', function() {
      // uncomment below and update the code to test the property realAddresses
      //var instance = new ProxiedMailApi.ProxyBindingListAttributes();
      //expect(instance).to.be();
    });

    it('should have the property proxyAddress (base name: "proxy_address")', function() {
      // uncomment below and update the code to test the property proxyAddress
      //var instance = new ProxiedMailApi.ProxyBindingListAttributes();
      //expect(instance).to.be();
    });

    it('should have the property isBrowsable (base name: "is_browsable")', function() {
      // uncomment below and update the code to test the property isBrowsable
      //var instance = new ProxiedMailApi.ProxyBindingListAttributes();
      //expect(instance).to.be();
    });

    it('should have the property receivedEmails (base name: "received_emails")', function() {
      // uncomment below and update the code to test the property receivedEmails
      //var instance = new ProxiedMailApi.ProxyBindingListAttributes();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ProxiedMailApi.ProxyBindingListAttributes();
      //expect(instance).to.be();
    });

    it('should have the property callbackUrl (base name: "callback_url")', function() {
      // uncomment below and update the code to test the property callbackUrl
      //var instance = new ProxiedMailApi.ProxyBindingListAttributes();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ProxiedMailApi.ProxyBindingListAttributes();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new ProxiedMailApi.ProxyBindingListAttributes();
      //expect(instance).to.be();
    });

  });

}));
