/**
 * ProxiedMail API
 * ProxiedMail API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ProxiedMailApi);
  }
}(this, function(expect, ProxiedMailApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ProxiedMailApi.ReceivedEmailApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReceivedEmailApi', function() {
    describe('apiV1ReceivedEmailsLinksProxyBindingIdGet', function() {
      it('should call apiV1ReceivedEmailsLinksProxyBindingIdGet successfully', function(done) {
        //uncomment below and update the code to test apiV1ReceivedEmailsLinksProxyBindingIdGet
        //instance.apiV1ReceivedEmailsLinksProxyBindingIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiV1ReceivedEmailsReceivedEmailIdGet', function() {
      it('should call apiV1ReceivedEmailsReceivedEmailIdGet successfully', function(done) {
        //uncomment below and update the code to test apiV1ReceivedEmailsReceivedEmailIdGet
        //instance.apiV1ReceivedEmailsReceivedEmailIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
